prev = Précédent
next = Suivant
steps-dnfdownloadupdate = Téléchargement de la mise à jour du Système…
steps-dnfinstallupdate = Installation de la mise à jour du Système…
imelangs-ch = Chinois
imelangs-ja = Japonais
imelangs-ko = Coréen
imelangs-vi = Vietnamien
imelangs-th = Thaïlandais
page-welcome = Bienvenue dans { $distro }
page-welcome-skipcfg = Passer la configuration
page-keyboard = Disposition du clavier
page-internet-skip = Je n'ai pas internet
page-internet-warn = Les codecs, les pilotes et les autres programmes utilisateur ne seront pas installés.
page-codecs-wiki = wiki
page-tweaks = Personnalisations du système
page-inputmethod-search-lang = Rechercher une langue…
page-codecs = Codecs et Pilotes
page-password-pw = Mot de passe
page-password-rp = Répéter le mot de passe
page-welcome-go = C'est parti
page-whoareyou = Qui êtes-vous ?
page-whoareyou-fullname = Nom complet
page-whoareyou-username = Nom d'utilisateur
page-whoareyou-error = Le nom d'utilisateur doit commencer par une lettre minuscule et contenir uniquement des caractères alphanumériques, des underscores (<tt>_</tt>) ou des tirets (<tt>-</tt>)
page-password = Créer un mot de passe
page-internet-ok = Vous êtes maintenant connecté à internet !
switch-crashreport = Envoyer les données relatives aux plantages
switch-codecs-desc = Appuyer sur "Suivant" pour passer l'installation
page-theme = Choisissez votre thème
page-theme-light = Clair
page-theme-dark = Sombre
page-finish-done = Terminé
page-error = Erreur
page-error-desc = Nous sommes désolés, mais une erreur inattendue s'est produite.
page-error-done = Terminé
page-error-retry = Recommencer
page-finish = Votre système est prêt
page-finish-desc = Nous espérons que vous apprécierez votre nouveau système d'exploitation !
page-categories-done = Terminé
categories = { $cat }
page-installing = Installation de votre Application
page-installing-desc = Cela ne prendra pas beaucoup de temps !
page-installing-loading = Chargement en cours…
page-language = Langue
flatpakening-name = Utiliser des Flatpaks à la place de paquets RPMs
flatpakening-desc = Cela améliore la sécurité du système en isolant les applications sélectionnées.
default = Par défaut
steps-driverscodecs = Installation des pilotes additionnels…
