prev = Précédent
next = Suivant
steps-dnfdownloadupdate = Téléchargement de la mise à jour du système…
steps-dnfinstallupdate = Installation de la mise à jour du système…
imelangs-ch = Chinois
imelangs-ja = Japonais
imelangs-ko = Coréen
imelangs-vi = Vietnamien
imelangs-th = Thaïlandais
page-welcome = Bienvenue dans { $distro }
page-welcome-skipcfg = Passer la configuration
page-keyboard = Disposition du clavier
page-internet-skip = Je n'ai pas Internet
page-internet-warn = Les codecs, les pilotes et d'autres applications ne seront pas installés sans un accès à Internet.
page-codecs-wiki = wiki
page-tweaks = Personnalisations du système
page-inputmethod-search-lang = Rechercher une langue…
page-codecs = Codecs et pilotes
page-password-pw = Mot de passe
page-password-rp = Répéter le mot de passe
page-welcome-go = C'est parti
page-whoareyou = Qui êtes-vous ?
page-whoareyou-fullname = Nom complet
page-whoareyou-username = Nom d'utilisateur
page-whoareyou-error = Le nom d'utilisateur doit commencer par une lettre minuscule et contenir uniquement des lettres minuscules, des chiffres, des tirets bas (<tt>_</tt>) ou des traits d'union (<tt>-</tt>).
page-password = Créer un mot de passe
page-internet-ok = Vous êtes connecté ! Appuyez sur Suivant pour continuer.
switch-crashreport = Envoyer les données de plantage
switch-codecs-desc = Activer cette option entraîne l'installation des codecs et pilotes propriétaires
page-theme = Choisissez votre thème
page-theme-light = Clair
page-theme-dark = Sombre
page-finish-done = Terminé
page-error = Erreur
page-error-desc = Il y a eu un petit souci.
page-error-done = Quitter
page-error-retry = Réessayer
page-finish = Prêt, feu, partez !
page-finish-desc = Nous espérons que vous aimerez Ultramarine !
page-categories-done = Terminé
categories = { $cat }
page-installing = Installation de vos applications
page-installing-desc = Ça ne sera pas long !
page-installing-loading = Chargement…
page-language = Langue
flatpakening-name = Utiliser des RPM à la place de Flatpaks
flatpakening-desc = Les Flatpaks sont plus sécurisés par défaut, tandis que les RPM prennent moins de place.
default = Par défaut
steps-driverscodecs = Installation des pilotes et des codecs…
skip = Passer
steps-script = Exécution du scriptlet…
steps-dnfdownloadapps = Téléchargement des applications…
steps-dnfinstallapps = Installation des applications…
imelangs-in = Indo-aryennes
imelangs-display = { $lang_name } ({ $native_lang_name })
page-language-search-lang = Rechercher une langue/locale…
page-welcome-ready = Préparons votre appareil.
page-keyboard-search-layout = Rechercher des dispositions de clavier…
page-keyboard-search-variant = Rechercher des variantes de claviers…
page-internet = Connectons-nous à Internet
page-internet-desc = Connectez-vous à Internet pour rester à la page.
page-internet-open = Se connecter à un réseau Wi-Fi
page-internet-portal = Se connecter avec un navigateur Web
page-analytics = Statistiques et signalement de plantages
page-crashreport = Signalement de plantages
page-crashreport-desc = Autorisez { $org } à recueillir des données de plantage pour identifier les bugs et vous aider.
page-crashreport-lbl1 = Toutes les données recueillies sont anonymes et chiffrées de bout en bout.
page-crashreport-lbl2 = Un ID de plantage vous sera donné et sera utilisé par l'assistance pour identifier ce qui s'est mal passé.
switch-crashreport-desc = Appuyez sur Suivant pour le garder désactivé
page-codecs-desc1 = Installez les codecs communs et les pilotes pour votre appareil.
page-codecs-desc2 = Consultez le { $wiki } si vous n'avez pas de connexion Internet.
switch-codecs = Installer les codecs et les pilotes
page-inputmethod = Méthodes de saisie supplémentaires
page-inputmethod-desc =
    Les langues avec des caractères non latins peuvent nécessiter un <b>éditeur de méthode de saisie (IME)</b> supplémentaire.
    Vous pouvez ignorer cette page si vous n'avez pas besoin de saisir dans une de ces langues.
    Plus d'informations sont disponibles sur { $wiki }.
page-inputmethod-add = Ajouter une méthode de saisie
page-inputmethod-wiki = le wiki
page-inputmethod-search-ims = Rechercher des IM/IME…
page-nightlight = Éclairage nocturne
page-nightlight-desc =
    Le soir, réchauffez les couleurs de votre écran pour réduire la fatigue visuelle.
    L'efficacité de l'Éclairage nocturne sur les difficultés d'endormissement n'a pas été prouvée.
switch-nightlight = Éclairage nocturne
page-theme-desc =
    Appropriez-vous ce système en y mettant une touche de couleur.
    Vous pouvez modifier cette option plus tard dans les paramètres.
page-theme-note = Il est possible que certaines applications ne respectent pas cette préférence.
page-browser = Sélection du navigateur
page-categories = À quelles fins utilisez-vous cet appareil ?
page-categories-confirm = Confirmer et configurer le système
page-installing-flatpak = Installation de { $n } Flatpaks…
