import { TdnPage } from "../page.slint";
import { Lang } from "../lang.slint";
import { HorizontalBox, Button, ScrollView } from "std-widgets.slint";
import { TdnText, TdnBtn, TdnInput } from "../components.slint";
import { Cfg } from "../cfg.slint";
import { Card } from "../slintcn/components/card.slint";
import { Label } from "../slintcn/components/label.slint";
import { Input } from "../slintcn/components/input.slint";

export component PasswordPage inherits TdnPage {
    pageid: "password";
    step_i: 1;

    Rectangle {
        height: 2rem;
    }

    Label {
        text: "Password";
        variant: required;
        clicked => {
            passwdinput.focus();
        }
    }

    passwdinput := Input {
        // TODO: impl
        text: "TODO impl!!!";
    }

    Rectangle {
        height: 2rem;
    }

    Label {
        text: "Repeat Password";
        variant: required;
        clicked => {
            repeatinput.focus();
        }
    }

    repeatinput := Input {
        // TODO: impl
        text: "TODO impl!!!";
    }
}
