prev = Previous
next = Next
steps-dnfdownloadupdate = 下载系统更新中…
steps-dnfinstallupdate = 安装系统更新中…
steps-dnfdownloadapps = 下载用户应用中…
steps-dnfinstallapps = 安装用户应用中…
steps-driverscodecs = 安装系统更新中…
imelangs-display = { $lang_name } ({ $native_lang_name })
page-welcome = 欢迎使用{ $distro }
page-welcome-go = 开始
page-welcome-skipcfg = 跳过系统配置
page-whoareyou = 创建新用户帐号
page-whoareyou-fullname = 名字
page-whoareyou-username = 用户名称
page-whoareyou-error =
    用戶名称
    - 首个英文字母须为小楷
    - 必须只包含数字、英文字母、底线(<tt>_</tt>)或连接号(<tt>-</tt>)
page-password = 创建密码
page-password-pw = 密码
page-password-rp = 重复密码
page-nightlight = 护眼模式
switch-nightlight = { page-nightlight }
page-theme = 选择主题
page-theme-desc = 选择主题色彩。您可以随时在设定更改此选项。
page-theme-note = 部分应用并不会对此设定有所反应。
page-theme-light = 浅色
page-theme-dark = 深色
page-browser = 选择浏览器
page-categories = 您会如何使用此设备？
page-categories-confirm = 确定并装配系统
page-categories-done = 完成
categories = { $cat }
page-installing = 正在安装您的应用
page-installing-desc = 请稍等一下
page-installing-loading = 加载中…
default = 默认
steps-script = 正在运行脚本…
imelangs-ch = 中文
imelangs-ja = 日本话
imelangs-ko = 韩国话
imelangs-vi = 越南语
imelangs-in = 印度语
imelangs-th = 泰语
page-language = 语言
page-language-search-lang = 搜索语言/区域设置…
page-welcome-ready = 来让我们帮你准备一下吧。
page-keyboard = 键盘布局
page-keyboard-search-layout = 搜索键盘布局…
page-keyboard-search-variant = 搜索键盘变体…
page-internet = 来让我们联网吧
page-internet-desc = 连接互联网以便得到最新资讯。
page-internet-skip = 我没有网络
page-internet-warn = 编解码器、驱动程序和某些应用程序在没有互联网的情况下无法安装。
page-internet-open = 连接到WiFi网络
page-internet-ok = 已连接！请点击下一步继续。
page-internet-portal = 使用网页浏览器登录
page-tweaks = 系统调整
page-codecs = 编解码器和驱动程序
page-codecs-desc1 = 为您的设备安装常用的媒体编解码器和驱动程序。
page-codecs-desc2 = 若您没有互联网连接，请查阅 { $wiki }。
page-codecs-wiki = 維基
switch-codecs = 安装编解码器和驱动程序
