default = Mặc định
prev = Trước
next = Sau
steps-dnfdownloadupdate = Đang tải xuống các cập nhật hệ thống…
steps-dnfinstallupdate = Đang cài đặt các cập nhật hệ thống…
steps-dnfdownloadapps = Đang tải xuống các ứng dụng…
steps-dnfinstallapps = Đang cài đặt các ứng dụng…
steps-driverscodecs = Đang cài đặt các trình điều khiển bổ sung…
imelangs-ch = Tiếng Trung
imelangs-ja = Tiếng Nhật
imelangs-ko = Tiếng Hàn
imelangs-vi = Tiếng Việt
imelangs-in = Tiếng Ấn Độ
imelangs-th = Tiếng Thái
imelangs-display = { $lang_name } ({ $native_lang_name })
page-welcome = Chào mừng đến với { $distro }
page-welcome-ready = Cùng chuẩn bị hệ thống mới của bạn.
page-welcome-go = Bắt đầu nào
page-welcome-skipcfg = Bỏ qua bước cấu hình
page-keyboard = Bố cục bàn phím
page-keyboard-search-layout = Tìm kiếm bố cục bàn phím…
page-keyboard-search-variant = Tìm kiếm biến thể bàn phím…
page-whoareyou = Giới thiệu bạn là ai?
page-whoareyou-fullname = Tên đầy đủ
page-whoareyou-username = Tên người dùng
page-whoareyou-error = Tên người dùng phải bắt đầu bằng chữ thường và chỉ được chứa chữ cái và số, dấu gạch dưới (<tt>_</tt>) hoặc dấu gạch ngang (<tt>-</tt>)
page-password = Hãy đặt mật khẩu
page-password-pw = Mật khẩu
page-password-rp = Nhập lại mật khẩu
page-internet = Hãy đưa bạn lên mạng
page-internet-desc = Kết nối mạng để có được điều tuyệt nhất và mới nhất.
page-internet-skip = Tôi không có mạng
page-codecs = Codec và trình điều khiển
page-codecs-desc1 = Cài đặt codec và trình điều khiển thiết bị độc quyền cho thiết bị của bạn.
page-codecs-desc2 = Tham khảo { $wiki } nếu bạn không có kết nối Internet.
page-codecs-wiki = wiki
switch-codecs = Cài đặt Codec và trình điều khiển
switch-codecs-desc = Nhấn tiếp để bỏ qua việc cài đặt
page-inputmethod = Phương thức nhập
page-inputmethod-desc1 = Bạn có thể <b>tùy chọn</b>cài đặt thêm { $ime }. Điều này giúp cho bạn có thể nhập ở một số ngôn ngữ nhất định Thay đổi này sẽ có hiệu lực sau khi bạn đăng nhập vào tài khoản của mình.
page-inputmethod-desc2 = Nhiều tùy chọn phương thức nhập tiếng Trung có thể khả dụng hơn với công cụ { $rime }, nhưng điều này yêu cầu cấu hình nâng cao và do đó không được khuyến nghị cho người mới bắt đầu.
page-inputmethod-desc3 = Bạn có thể tìm hiểu thêm thông tin ở { $wiki }.
page-inputmethod-ime = trình điều khiểu phương thức nhập (IME)
page-inputmethod-rime = Rime
page-inputmethod-wiki = wiki
page-inputmethod-search-lang = Tìm kiếm ngôn ngữ…
page-inputmethod-search-ims = Tìm kiếm IMs/IMEs…
page-nightlight = Ánh sáng đêm
page-nightlight-lbl1 = Phủ màn hình bằng tông màu ấm vào ban đêm để giảm mỏi mắt.
page-nightlight-lbl2 = Ánh sáng đêm không được chứng minh là hỗ trợ việc mất ngủ.
switch-nightlight = Ánh sáng đêm
page-theme = Chọn chủ đề bạn muốn
page-theme-desc =
    Biến hệ thống này thành của riêng bạn với một chút màu sắc.
    Bạn có thể thay đổi tùy chọn này sau trong phần cài đặt.
page-theme-note = Một số ứng dụng sẽ không tuân theo tùy chọn này.
page-theme-light = Sáng
page-theme-dark = Tối
page-browser = Chọn trình duyệt
page-categories = Bạn sẽ dùng thiết bị này như thế nào?
page-categories-confirm = Xác nhận và cài đặt hệ thống
page-categories-done = Xong
categories = { $cat }
page-installing = Dang cài đặt các ứng dụng
page-installing-desc = Sẽ không lâu lắm đâu!
page-installing-loading = Đang tải…
page-finish = Hệ thống của bạn đã sẵn sàng
page-finish-desc = Tận hưởng hệ thống mới của bạn!
page-finish-done = Xong
page-error = Lỗi
page-error-desc = Rất tiếc, đã có lỗi xảy ra.
page-error-done = Xong
page-error-retry = Thử lại
