default = Výchozí
prev = Předchozí
next = Další
steps-dnfdownloadupdate = Stahování systémových aktualizací…
steps-dnfinstallupdate = Instalace systémových aktualizací…
steps-dnfdownloadapps = Stahování Aplikací…
steps-dnfinstallapps = Instalace Aplikací…
steps-driverscodecs = Instalace Ovladačů a Kodeků…
imelangs-ch = Čínština
imelangs-ja = Japonština
imelangs-ko = Korejština
imelangs-vi = Vietnamština
imelangs-in = Indické
imelangs-th = Thajština
imelangs-display = { $lang_name } ({ $native_lang_name })
page-welcome = Vítejte v { $distro }
page-welcome-ready = Připravme Vaše zařízení.
page-welcome-go = Pojďme
page-welcome-skipcfg = Přeskočit konfiguraci
page-keyboard = Rozložení klávesnice
page-keyboard-search-layout = Hledat rozložení klávesnice…
page-keyboard-search-variant = Hledat varianty rozložení klávesnice…
page-whoareyou = Kdo jste?
page-whoareyou-fullname = Celé jméno
page-whoareyou-username = Uživatelské jméno
page-whoareyou-error = Uživatelské jméno musí začínat malým písmenem a musí obsahovat pouze písmena, čísla, podtržítka (<tt>_</tt>) nebo pomlčky (<tt>-</tt>).
page-password = Vytvořte heslo
page-password-pw = Heslo
page-password-rp = Potvrďte heslo
page-internet = Pojďme se připojit
page-internet-desc = Připojte se k Internetu k získání toho nejnovějšího a nejlepšího.
page-internet-skip = Nemám připojení k Internetu
page-internet-warn = Kodeky, ovladače a některé aplikace nebudou nainstalovány bez internetového připojení.
page-internet-open = Připojit k síti WiFi
page-analytics = Analýza a Hlášení nehod
page-crashreport = Hlášení nehod
page-crashreport-desc = Povolte { $org } sbírání dat o pádech k odhalení chyb a Vaší pomoci.
page-crashreport-lbl1 = All data collected is anonymous and end-to-end encrypted.
page-crashreport-lbl2 = Dostanete ID pádu, které pomůže podpoře zjistit, co se stalo.
switch-crashreport = Poslat data havárie
page-codecs = Kodeky a ovladače
switch-codecs = Nainstalovat kodeky a ovladače
switch-codecs-desc = Stiskněte další pro přeskočení instalace
page-inputmethod = Metody vstupu
page-inputmethod-search-lang = Hledat jazyk…
page-inputmethod-search-ims = Hledat IMs/IMEs…
page-nightlight = Noční osvětlení
page-nightlight-desc =
    V noci zbarví obrazovku teplým tónem, pro snížení únavy očí.
    Není prokázáno, že by noční světlo pomáhalo při potížích s usínáním.
switch-nightlight = Noční osvětlení
page-theme = Vyberte si motiv
page-theme-desc =
    Přizpůsobte si system barevným nádechem.
    Tuto možnost si můžete později změnit v nastavení.
page-theme-note = Některé aplikace nemusí toto nastavení respektovat.
page-theme-light = Světlý
page-theme-dark = Tmavý
page-browser = Výběr prohlížeče
page-categories = K čemu toto zařízení využíváte?
page-categories-confirm = Potvrdit a nastavit systém
page-categories-done = Hotovo
page-installing = Instalace Vašich aplikací
page-installing-desc = Nepotrvá to dlouho!
page-installing-loading = Načítání…
page-finish = Váš systém je připraven
page-finish-desc = Doufáme, že si svůj čerstvý systém užijete!
page-finish-done = Hotovo
page-error = Chyba
page-error-desc = Omlouváme se, ale vyskytla se nečekaná chyba.
page-error-done = Hotovo
page-error-retry = Opakovat
steps-script = Spuštění Skriptletu…
switch-crashreport-desc = Stiskněte další pro vypnutí
page-codecs-desc1 = Nainstalovat proprietární kodeky médií a ovladače pro vaše zařízení.
page-codecs-desc2 = Nahlédněte do { $wiki } pokud nemáte připojení k Internetu.
page-codecs-wiki = wiki
page-inputmethod-wiki = wikipedie
categories = { $cat }
page-internet-ok = Nyní jste připojeni k Internetu! Pro pokračování stiskněte Další.
page-installing-flatpak = Instaluji { $n } flatpaků…
skip = Přeskočit
page-language = Jazyk
page-language-search-lang = Hledat Jazyk…
