default = 預設值
prev = 上一頁
next = 下一頁
steps-dnfdownloadupdate = 下載系統更新中…
steps-dnfinstallupdate = 更新中…
steps-script = 執行手稿中…
steps-dnfdownloadapps = 下載程式中…
steps-dnfinstallapps = 安裝程式中…
steps-driverscodecs = 安裝驅動程式及編解碼器中…
imelangs-ch = 中文
imelangs-ja = 日文
imelangs-ko = 韓文
imelangs-vi = 越南語
imelangs-in = 印雅語支
imelangs-th = 泰文
imelangs-display = { $lang_name }（{ $native_lang_name }）
page-welcome = 歡迎使用{ $distro }
page-welcome-ready = 一起準備好新的系統吧。
page-welcome-go = 開始
page-welcome-skipcfg = 略過系統配置
page-keyboard = 鍵盤配置
page-keyboard-search-layout = 搜尋鍵盤配置…
page-keyboard-search-variant = 搜尋鍵盤變體…
page-whoareyou = 您是誰？
page-whoareyou-fullname = 名字
page-whoareyou-username = 用戶名稱
page-whoareyou-error = 用戶名稱須以小楷字母開始，並只以數字、小楷字母、底線(<tt>_</tt>)或連接號(<tt>-</tt>)組成。
page-password = 創建密碼
page-password-pw = 密碼
page-password-rp = 重覆密碼
page-internet = 網絡連線
page-internet-desc = 連接互聯網，取得最新、最好的。
page-internet-skip = 我不能連上網
page-internet-warn = 編解碼器、驅動程式及使用者程式將不被安裝。
page-internet-open = 連接Wi-Fi網絡
page-codecs = 編解碼器及驅動程式
page-codecs-desc1 = 安裝多媒體編解碼器與驅動程式。
page-codecs-desc2 = 若未能連上網絡，請參考{ $wiki }。
page-codecs-wiki = 我們的wiki
switch-codecs = 安裝專利媒體編解碼器與驅動程式
switch-codecs-desc = 啟用此以安裝多媒體編解碼器與驅動程式
page-inputmethod = 更多輸入法
page-inputmethod-wiki = wiki
page-inputmethod-search-lang = 搜尋語言…
page-inputmethod-search-ims = 搜尋輸入法…
page-nightlight = 護眼模式
page-nightlight-desc =
    夜間時調教至較暖和的色溫有助減少對雙眼的傷害。
    護眼模式並未證實能改善睡眠。
switch-nightlight = 護眼模式
page-theme = 選擇主題
page-theme-desc =
    選擇主題色彩。
    您可以隨時在設定更改此選項。
page-theme-note = 部分程式並不會對此設定有所反應。
page-theme-light = 淺色
page-theme-dark = 深色
page-browser = 選擇瀏覽器
page-categories = 您會如何使用此設備？
page-categories-confirm = 確定並裝配系統
page-categories-done = 完成
categories = { $cat }
page-installing = 正在安裝您的應用程式
page-installing-desc = 很快就會完成，請稍等吧！
page-installing-loading = 加載中…
page-finish = 準備好嗎？
page-finish-desc = 希望您享受您的新系統吧！
page-finish-done = 完成
page-error = 錯誤
page-error-desc = 我們遇到了問題。
page-error-done = 關閉
page-error-retry = 重試
skip = 跳過
page-internet-ok = 您已連上網絡！按下一頁繼續。
page-internet-portal = 以瀏覽器登入
page-tweaks = 系統調整
page-inputmethod-desc =
    具有非拉丁文字的語言或需要<b>輸入法</b>。
    按「追加輸入法」以繼續。
    請參考{ $wiki }瞭解更多。
page-inputmethod-add = 追加輸入法
page-installing-flatpak = 正在安裝 { $n } 個 Flatpak……
page-language = 語言
page-language-search-lang = 搜尋語言……
flatpakening-name = 以 RPM 取代 Flatpak
flatpakening-desc = Flatpak 比較安全；RPM 利用較少儲存空間。
page-analytics = 分析及錯誤彙報
page-crashreport = 錯誤彙報
page-crashreport-desc = 允許{ $org }收集錯誤訊息，以便尋找問題及提供協助。
page-crashreport-lbl1 = 所有訊息均是匿名並具端至端加密。
page-crashreport-lbl2 = 你會收到錯誤 ID 以便支援人員找出錯處。
switch-crashreport = 傳送錯誤訊息
switch-crashreport-desc = 按下一頁保持關閉
