name: Rust
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  rust:
    uses: FyraLabs/actions/.github/workflows/rust.yml@main
    with:
      test-container: '{"image": "ghcr.io/terrapkg/builder:f41"}'
      test-pre: |
        dnf install -y openssl-devel libhelium-devel gtk4-devel 'pkgconfig(glib-2.0)' 'pkgconfig(libattr)' 'pkgconfig(gnome-desktop-4)' clang-devel perl-FindBin gcc make clang
